### ISSUE TITLE
why show so many duplicate symbol with XLForm.

### ISSUE THREAD

**Issue by jbasttdi** [xmartlabs/XLForm#311]
![tb](https://cloud.githubusercontent.com/assets/4523109/7154724/7e0e4948-e38b-11e4-9d4f-393837d6bb4b.png)

**Comment by jbasttdi** [comment]
I think in XLFormDescriptor.h and so on .h files,
```
NSString * const XLFormErrorDomain;
NSString * const XLValidationStatusErrorKey;

typedef NS_ENUM(NSInteger, XLFormErrorCode)
{
    XLFormErrorCodeGen = -999,
    XLFormErrorCodeRequired = -1000
};
```
should add "static" and updated to
'''
static NSString * const XLFormErrorDomain;
static NSString * const XLValidationStatusErrorKey;

typedef NS_ENUM(NSInteger, XLFormErrorCode)
{
    XLFormErrorCodeGen = -999,
    XLFormErrorCodeRequired = -1000
};
'''

**Comment by jbasttdi** [comment]
There are some errors in the master rep.
when i use pod 'XLForm' it's ok,no Error!
but when i use pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git' it will show error:
```
duplicate symbol _XLValidationStatusErrorKey in:
    /Users/jbas/Library/Developer/Xcode/DerivedData/tt-hdhhfcpmpbjuktawhyinjinidylo/Build/Intermediates/tt.build/Debug-iphonesimulator/tt.build/Objects-normal/x86_64/XViewController.o
    /Users/jbas/Library/Developer/Xcode/DerivedData/tt-hdhhfcpmpbjuktawhyinjinidylo/Build/Products/Debug-iphonesimulator/libPods-XLForm.a(XLFormDescriptor.o)
duplicate symbol _XLFormErrorDomain in:
    /Users/jbas/Library/Developer/Xcode/DerivedData/tt-hdhhfcpmpbjuktawhyinjinidylo/Build/Intermediates/tt.build/Debug-iphonesimulator/tt.build/Objects-normal/x86_64/XViewController.o
    /Users/jbas/Library/Developer/Xcode/DerivedData/tt-hdhhfcpmpbjuktawhyinjinidylo/Build/Products/Debug-iphonesimulator/libPods-XLForm.a(XLFormDescriptor.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
My class is so simple,only one XViewController file as below.
![err 2](https://cloud.githubusercontent.com/assets/4523109/7156134/c2551824-e396-11e4-8826-084dd167d285.jpeg)

**Comment by pastorin** [comment]
Hello @jbasttdi,

This was fixed in the last commit of master repository.

Regards

**Comment by frandelarosa** [comment]
I have the same issue!

**Comment by richarddwalsh** [comment]
This issue is still persistent.

**Comment by yoongfook** [comment]
I am still facing this issue!

**Comment by lm2s** [comment]
Me too, even using the latest commit.

**Comment by lm2s** [comment]
@frandelarosa @richarddwalsh @yoongfook I had this issue when using the latest CocoaPod, I fixed it by using the ":head" option on the podfile and retrieving the latest version from master.

**Comment by jacobbullock** [comment]
This is still an issue for me as well.

**Comment by siuying** [comment]
fixed after I use 3.0.0 version.

**Comment by joaopedrok** [comment]
I've got the same issue and i don't know how to fix it.

**Comment by conradwt** [comment]
I haven't seen this issue with either with Xcode 6.4 or Xcode 7 Beta 4 running on OS X 10.10 or 10.11.

**Comment by siuying** [comment]
@joaopedrok have you try to use latest version? in your podfile:

```
pod 'XLForm', '~> 3.0.1'
```

**Comment by tciuro** [comment]
The problem still persists with the latest release (3.1.1). I added the following to the posfile:

    pod 'XLForm', '~> 3.1.1'

When I build `XLForm.xcworkspace > XLForm` I get 196 duplicate symbols. If I try with `XLForm.xcodeproj` I get:

	Ld /Users/tito/Library/Developer/Xcode/DerivedData/XLForm-dfphndxrjypkeubfcchttjnngbzw/Build/Products/Debug-iphonesimulator/XLForm.framework/XLForm normal x86_64
	    cd "/Users/tito/Desktop/iOS World/XLForm"
	    export IPHONEOS_DEPLOYMENT_TARGET=8.0
	    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/tito/Library/Developer/Xcode/DerivedData/XLForm-dfphndxrjypkeubfcchttjnngbzw/Build/Products/Debug-iphonesimulator -F/Users/tito/Library/Developer/Xcode/DerivedData/XLForm-dfphndxrjypkeubfcchttjnngbzw/Build/Products/Debug-iphonesimulator -filelist /Users/tito/Library/Developer/Xcode/DerivedData/XLForm-dfphndxrjypkeubfcchttjnngbzw/Build/Intermediates/XLForm.build/Debug-iphonesimulator/XLForm.build/Objects-normal/x86_64/XLForm.LinkFileList -install_name @rpath/XLForm.framework/XLForm -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lXLForm -framework CoreGraphics -framework Foundation -framework UIKit -fobjc-arc -fobjc-link-runtime -lPods -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/tito/Library/Developer/Xcode/DerivedData/XLForm-dfphndxrjypkeubfcchttjnngbzw/Build/Intermediates/XLForm.build/Debug-iphonesimulator/XLForm.build/Objects-normal/x86_64/XLForm_dependency_info.dat -o /Users/tito/Library/Developer/Xcode/DerivedData/XLForm-dfphndxrjypkeubfcchttjnngbzw/Build/Products/Debug-iphonesimulator/XLForm.framework/XLForm

	ld: library not found for -lXLForm

Any ideas? :-/
